# e kentwood


path = "R_SC_S_C2F"
pathAzimuth = 0.0
intakeAzimuth = -40.0
# practice
#driveStopDistance = 44
#intakeStopDistance = 35
# comp
driveStopDistance = 35
intakeStopDistance = 15
drive = 0.15
strafe = -0.15
