#            ____   _____        _______ ____    _   _ ____
#           |  _ \ / _ \ \      / / ____|  _ \  | | | |  _ \
#           | |_) | | | \ \ /\ / /|  _| | |_) | | | | | |_) |
#           |  __/| |_| |\ V  V / | |___|  _ <  | |_| |  __/
#           |_|    \___/  \_/\_/  |_____|_| \_\  \___/|_|
#  ____        __             _ _     ____       _   _   _
# |  _ \  ___ / _| __ _ _   _| | |_  / ___|  ___| |_| |_(_)_ __   __ _ ___
# | | | |/ _ \ |_ / _` | | | | | __| \___ \ / _ \ __| __| | '_ \ / _` / __|
# | |_| |  __/  _| (_| | |_| | | |_   ___) |  __/ |_| |_| | | | | (_| \__ \
# |____/ \___|_|  \__,_|\__,_|_|\__| |____/ \___|\__|\__|_|_| |_|\__, |___/
#                                                                |___/
# These settings are used if not overridden in ~lvuser/powerup.toml on roboRIO

[POWERUP]
description = "Stryke Force 2018 POWER UP"

[PATHS.TEST1]
waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 5.0, y = 4.5, angle = 90.0},
  {x = 12.5, y = 9.5, angle = 0.0},
  {x = 15.5, y = 9.5, angle = 0.0},
  {x = 22.5, y = 4.0, angle = -90.0},
  {x = 22.5, y = -10.0, angle = -90.0},
  {x = 15.0, y = -17.5, angle = -180.0},
  {x = 10.0, y = -17.5, angle = -180.0},
  {x = 5.0, y = -10.0, angle = 90.0},
  {x = 5.0, y = -5.0, angle = 90.0},
  {x = 0.0, y = 0.0, angle = 0.0},
]
fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.050    # sec
max_velocity     = 2.5   # m/sec
max_acceleration = 5.0  # m/sec/sec
max_jerk         = 50.0  # m/sec/sec/sec

###############################################################################
##
## Talon Configurations for Third Coast Swerve Drive
##
###############################################################################
[THIRDCOAST.WHEEL]
  driveSetpointMax = 5000

[[TALON]]
  name = "azimuth"
  talonIds = [0, 1, 2, 3]
  [selectedFeedbackSensor]
    feedbackDevice = "CTRE_MagEncoder_Relative"
  [motionMagic]
    acceleration = 10000
    cruiseVelocity = 800
  [[closedLoopProfile]] # slot 0 MotionMagic
    pGain = 15.0
    iGain = 0.0
    dGain = 150.0
    fGain = 1.0
    iZone = 0
    allowableClosedLoopError = 0

[[TALON]]
  name = "drive"
  talonIds = [10, 11, 12, 13]
  [selectedFeedbackSensor]
    feedbackDevice = "CTRE_MagEncoder_Relative"
  [currentLimit]
    continuous = 40
    peak = 0
    peakDuration = 0
  [[closedLoopProfile]] # slot 0 Velocity
    pGain = 0.1
    iGain = 0.0
    dGain = 1.0
    fGain = 0.03
    iZone = 0
    allowableClosedLoopError = 0
