#            ____   _____        _______ ____    _   _ ____
#           |  _ \ / _ \ \      / / ____|  _ \  | | | |  _ \
#           | |_) | | | \ \ /\ / /|  _| | |_) | | | | | |_) |
#           |  __/| |_| |\ V  V / | |___|  _ <  | |_| |  __/
#           |_|    \___/  \_/\_/  |_____|_| \_\  \___/|_|
#  ____        __             _ _     ____       _   _   _
# |  _ \  ___ / _| __ _ _   _| | |_  / ___|  ___| |_| |_(_)_ __   __ _ ___
# | | | |/ _ \ |_ / _` | | | | | __| \___ \ / _ \ __| __| | '_ \ / _` / __|
# | |_| |  __/  _| (_| | |_| | | |_   ___) |  __/ |_| |_| | | | | (_| \__ \
# |____/ \___|_|  \__,_|\__,_|_|\__| |____/ \___|\__|\__|_|_| |_|\__, |___/
#                                                                |___/
# These settings are used if not overridden in ~lvuser/powerup.toml on roboRIO

[POWERUP]
description = "Stryke Force 2018 POWER UP"
isolatedTestMode = false

[POWERUP.JOYSTICK]
  deadband  = 0.05
  expoScale = 0.5
  rateLimit = 0.04

[POWERUP.CLIMBER]
  upOutput   = 1.0
  stopOutput = 0.1

[POWERUP.FLIPPER]
  upOutput     = 0.5
  downOutput   = -0.2
  upPosition   = 1000
  downPosition = 200

[POWERUP.INTAKE]
  loadOutput = 0.5
  holdOutput = 0.1

[POWERUP.LIFT]
  upOutput   = 0.2
  downOutput = -0.2
  stopOutput = 0.0
  
  absoluteTolerance = 10
