#            ____   _____        _______ ____    _   _ ____
#           |  _ \ / _ \ \      / / ____|  _ \  | | | |  _ \
#           | |_) | | | \ \ /\ / /|  _| | |_) | | | | | |_) |
#           |  __/| |_| |\ V  V / | |___|  _ <  | |_| |  __/
#           |_|    \___/  \_/\_/  |_____|_| \_\  \___/|_|
#                         _           ____  ___ ___
#               _ __ ___ | |__   ___ |  _ \|_ _/ _ \
#              | '__/ _ \| '_ \ / _ \| |_) || | | | |
#              | | | (_) | |_) | (_) |  _ < | | |_| |
#              |_|  \___/|_.__/ \___/|_| \_\___\___/
#
[POWERUP]
description = "Stryke Force 2018 POWER UP"
isolatedTestMode = false

[POWERUP.JOYSTICK]
 deadband = 0.05
 expoScale = 0.5
 rateLimit = 0.04

[PATHS.LEFT]
waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 8.0, y = -0.2, angle = 0.0},
  {x = 10.0, y = -0.4, angle = 0.0},
  {x = 11.5, y = -0.7, angle = 0.0},
  {x = 12.0, y = -1.5, angle = -90.0},
]
fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.05  # sec
max_velocity     = 1.7   # m/sec
max_acceleration = 2.0   # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec
p_azimuth        = -0.004

[PATHS.CENTERLEFT]
waypoints = [
  {x = 0.0, y = 0.0, angle = 35.0},
  {x = 3.75, y = 2.8, angle = 40.0},
  {x = 7.5, y = 5.16, angle = 0.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.05  # sec
max_velocity     = 1.7   # m/sec
max_acceleration = 2.0   # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec
p_azimuth        = -0.004

[PATHS.CENTERRIGHT]
waypoints = [
  {x = 0.0, y = 0.0, angle = -35.0},
  {x = 3.75, y = -2.8, angle = -35.0},
  {x = 7.8, y = -3.5, angle = 0.0},
]
fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.05  # sec
max_velocity     = 1.7   # m/sec
max_acceleration = 2.0   # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec
p_azimuth        = -0.004

[PATHS.CENTERRIGHTEXCHANGE]

waypoints = [
  {x = 0.0, y = 0.0, angle = -35.0},
  {x = 7.5, y = -3.7, angle = 0.0},
  {x = 6.0, y = -2.5, angle = -90.0},
  {x = 6.0, y = -1.0, angle = -90.0},
  {x = 5.0, y = -1.7, angle = -180.0},
  {x = 0.0, y = 1.5, angle = -180.0}

]
fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.05  # sec
max_velocity     = 1.7   # m/sec
max_acceleration = 2.0   # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec
p_azimuth        = -0.004

[THIRDCOAST.SWERVE]
  length = 20.625
  width  = 26.125

#[[TALON]]
#  name = "azimuth"
#  talonIds = [0, 1, 2, 3]
#  [TALON.selectedFeedbackSensor]
#    feedbackDevice = "CTRE_MagEncoder_Relative"
#  [TALON.motionMagic]
#    acceleration = 10000
#    cruiseVelocity = 800
#  [[TALON.closedLoopProfile]] # slot 0 MotionMagic
#    pGain = 15.0
#    iGain = 0.0
#    dGain = 150.0
#    fGain = 1.0
#    iZone = 0
#    allowableClosedLoopError = 0
#
#[[TALON]]
#  name = "drive"
#  talonIds = [10, 11, 12, 13]
#  [TALON.selectedFeedbackSensor]
#    feedbackDevice = "CTRE_MagEncoder_Relative"
#  [TALON.currentLimit]
#    continuous = 40
#    peak = 0
#    peakDuration = 0
#  [[TALON.closedLoopProfile]] # slot 0 Velocity
#    pGain = 0.1
#    iGain = 0.0
#    dGain = 1.0
#    fGain = 0.03
#    iZone = 0
#    allowableClosedLoopError = 0
#
#[[TALON]]
#  name = "climber"
#  talonIds = [20, 21]
#  [TALON.selectedFeedbackSensor]
#    feedbackDevice = "CTRE_MagEncoder_Relative"
#  [TALON.output]
#    neutralMode = "Brake"

[[TALON]]
  name = "intake"
  talonIds = [30, 31]
  [TALON.selectedFeedbackSensor]
    feedbackDevice = "CTRE_MagEncoder_Relative"
  [TALON.output]
    neutralMode = "Brake"
  [TALON.currentLimit]
    continuous = 10
    peak = 0
    peakDuration = 0

[[TALON]]
  name = "lift-master"
  talonIds = [50]
  [TALON.selectedFeedbackSensor]
    feedbackDevice = "CTRE_MagEncoder_Relative"
    phaseSensor = true
  [TALON.output]
    neutralMode = "Brake"
  [TALON.currentLimit]
    continuous = 40
    peak = 0
    peakDuration = 0
  [TALON.softLimit.forward]
    limit = 18500
    enabled = true
  [TALON.softLimit.reverse]
    limit = 1000
    enabled = true
  [TALON.motionMagic] # down
    acceleration = 2500  # 10000 up
    cruiseVelocity = 750 # 1500
  [[TALON.closedLoopProfile]] # slot 0 MotionMagic
    pGain = 1.0
    iGain = 0.0
    dGain = 75.0
    fGain = 0.4
    iZone = 0
    allowableClosedLoopError = 0

[[TALON]]
  name = "lift-slave"
  talonIds = [51]
  [TALON.currentLimit]
    continuous = 40
    peak = 0
    peakDuration = 0

[[TALON]]
  name = "shoulder"                                   
  talonIds = [40]                             
  [TALON.selectedFeedbackSensor]               
    feedbackDevice = "CTRE_MagEncoder_Relative"                            
  [TALON.output]                                  
    neutralMode = "Brake" 
  [TALON.softLimit.forward]
    limit = 0
    enabled = false
  [TALON.softLimit.reverse]
    limit = 0
    enabled = true
  [TALON.limitSwitch.forward]
    source = "FeedbackConnector"
    normal = "NormallyOpen"
  [TALON.currentLimit]
    continuous = 10
    peak = 0
    peakDuration = 0
  [TALON.motionMagic]
    acceleration = 5000
    cruiseVelocity = 1000
  [[TALON.closedLoopProfile]] # slot 0 MotionMagic
    pGain = 1.0
    iGain = 0.0
    dGain = 50.0
    fGain = 1.1
    iZone = 0
    allowableClosedLoopError = 0


#[[TALON]]
#  name = "flipper"                                   
#  talonIds = [60]                             
#  [TALON.selectedFeedbackSensor]               
#    feedbackDevice = "CTRE_MagEncoder_Relative"                            
#  [TALON.output]                                  
#    neutralMode = "Brake" 
#  [TALON.softLimit.forward]
#    limit = 1400
#    enabled = true
#  [TALON.softLimit.reverse]
#    limit = 100
#    enabled = true
